### ISSUE TITLE
a BytesBuf has a "void*buf" and "int len", but no means to set content

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_rule_engine_plugin_python#104]
- [x] 4-2-stable
- [x] main
---
The iRODS primitive data type ` bytesBuf_t`, may be  instantiated in the Python RE plugin as **irods_types.BytesBuf( )**, but it is impractical as an input buffer parameter for the microservice` msiDataObjWrite` (which accepts it based on its type) because its content and length may not be set.  (Strings and bytestrings are also impractical for the purpose, as the write is curtailed at the first NUL character  in the string's content, regardless of the length parameter specified to  ` msiDataObjWrite`). 

I propose adding a method, **setbuf(const char*c, int len)** , whereby this can be done.

It remains to be seen how boost-python deals with the destruction of such objects when they go away.  Possibly all that would be needed is to add a "\_\_del\_\_ method".

**Comment by trel** [comment]
two additional options...
1) would it be better/easier to have the first NUL of a string of bytestring not be made so important?
or
2) have the `bytesBuf_t` always 'self heal' and make it automatically have the correct length based on its content?

**Comment by d-w-moore** [comment]
`bytesBuf_t` appears to already do the right thing, but the difficulty we have in the Python RE plugin is the inability to set its content (absent this [modification](https://github.com/d-w-moore/irods_rule_engine_plugin_python/commits/104.42s)) If we consider these two implementations of a rule to write from a local file into a data object (adapted from [here](https://groups.google.com/g/iROD-Chat/c/p54KDZRQ-zE/m/DYUXOKnvAwAJ) ): 
```
def py_obj_write_1(args,callback,rei):
    dest_file = args[0]
    with open('/tmp/file.tar.gz', 'rb') as file_:
        binarycontent = (file_.read())
        ret_val = callback.msiDataObjOpen(('objPath={}++++openFlags=O_WRONLY''O_CREAT''O_TRUNC').format( dest_file), 0)
        f = ret_val['arguments'][1]
        callback.msiDataObjWrite(f, binarycontent, len(binarycontent))
        callback.msiDataObjClose(f, 0)

def py_obj_write_2(args,callback,rei):
    dest_file = args[0]
    with open('/tmp/file.tar.gz', 'rb') as file_:
        binarycontent = (file_.read())
        b = BytesBuf()
        b.setbuf(binarycontent, len(binarycontent))
        ret_val = callback.msiDataObjOpen(('objPath={}++++openFlags=O_WRONLY''O_CREAT''O_TRUNC').format( dest_file), 0)
        f = ret_val['arguments'][1]
        callback.msiDataObjWrite(f, b, b.len)
        callback.msiDataObjClose(f, 0)
```
The first attempts the write with a string as the buffer, which Python can handle even with NULs, but the plugin seems to translate it as `const char*` . So if there's a NUL in the string, then regardless of specifying the length param in the `msiDataObjWrite`, the whole buffer never makes it into the microservice. The BytesBuf_t is the proper solution, but the Python plugin even in its latest release doesn't actually let you set the content; it only allows you to instantiate a blank object with no content.

**Comment by trel** [comment]
Right, so `setbuf` appears to be the answer.

And the `__del__` feels correct as well.   The tests will let us know if it creates a double-free anywhere, but I'd be surprised.
