### ISSUE TITLE
CMake/Packaging references incorrect Python dependency

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_rule_engine_plugin_python#133]
https://github.com/irods/irods_rule_engine_plugin_python/blob/381eb089bac1fad0dbf403ae6fad92f20d78e8b7/CMakeLists.txt#L159
https://github.com/irods/irods_rule_engine_plugin_python/blob/381eb089bac1fad0dbf403ae6fad92f20d78e8b7/CMakeLists.txt#L163

These package names aren't supported anymore in newer distributions either (e.g Ubuntu 20). They should be updated to the appropriate package name.
- python3-dev for Ubuntu
- python3-devel for EL-based distros

**Comment by SwooshyCueb** [comment]
Do we actually need to declare a dependency on the development packages? If not, let's reduce this to a runtime package or set of runtime packages.

**Comment by trel** [comment]
Agreed - dev is only required for building, or we've got things in the wrong places.

**Comment by SwooshyCueb** [comment]
For Ubuntu/Debian, we will need `libpythonX.Y` (`libpython3.8` for py3 on Ubuntu 20.04, for example). This also pulls in the entire stdlib.
For EL, we will need `pythonX-libs` (`python3-libs` for py3, for example). I *think* this also pulls in the entire stdlib.

We may need additional packages if we rely on the presence of any non-stdlib modules.
