### ISSUE TITLE
test_python_continuation_to_native_58 fails in lib.delayAssert

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_rule_engine_plugin_python#149]
When running plugin version 4.3.0.1 in server built from tip of main, `test_python_continuation_to_native_58` fails.
The same failure occurs in my PR #140, so presumably this has not been fixed yet.

The test is running in an Ubuntu 20.04 container, using postgres.

Here's some of the test output. I've put a more complete log [here](https://gist.github.com/SwooshyCueb/c75d0614d0014ce09d6f1e7cd0dde9d7).

```
 --- IrodsSession: icommand executed by [otherrods#tempZone] [iput /tmp/tmpxlpn2e1n] --- 
Assert Command: iput /tmp/tmpxlpn2e1n
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found


======================================================================
FAIL: test_python_continuation_to_native_58 (irods.test.test_python_rule_engine_plugin.Test_Python_Rule_Engine_Plugin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_python_rule_engine_plugin.py", line 91, in test_python_continuation_to_native_58
    lib.delayAssert(
  File "/var/lib/irods/scripts/irods/lib.py", line 565, in delayAssert
    raise AssertionError
AssertionError
```

**Comment by alanking** [comment]
I believe this is fixed by changes made in #171. We observed this test failure in the run up to 4.3.1.0 and the tests are now passing.
