### ISSUE TITLE
Usability with irods 4.3.0  Debian 11 packages?

### ISSUE THREAD

**Issue by bzizou** [irods/irods_rule_engine_plugin_python#156]
I have conflicts with python3 and python2 when I try to use the python plugin on a Debian 11. For example, I had to install the "exifread" python module into python2, but when I try to load it from the core.py, the irods server fails with errors involving python3 :

From irods.log:

{"log_category":"legacy","log_facility":"local0","log_level":"error","log_message":"caught python exception: Traceback (most recent call last):\n  File \"/usr/lib/python3.9/decimal.py\", line 3, in <module>\n    from _decimal import *\nImportError: /usr/lib/python3.9/lib-dynload/_decimal.cpython-39-x86_64-linux-gnu.so: undefined symbol: PyFloat_Type\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/etc/irods/core.py\", line 11, in <module>\n    import exifread\n  File \"/usr/lib/python3/dist-packages/exifread/__init__.py\", line 8, in <module>\n    from .classes import ExifHeader\n  File \"/usr/lib/python3/dist-packages/exifread/classes.py\", line 7, in <module>\n    from .utils import Ratio\n  File \"/usr/lib/python3/dist-packages/exifread/utils.py\", line 7, in <module>\n    from fractions import Fraction\n  File \"/usr/lib/python3.9/fractions.py\", line 6, in <module>\n    from decimal import Decimal\n  File \"/usr/lib/python3.9/decimal.py\", line 8, in <module>\n    from _pydecimal import *\n  File \"/usr/lib/python3.9/_pydecimal.py\", line 440, in <module>\n    import contextvars\n  File \"/usr/lib/python3.9/contextvars.py\", line 1, in <module>\n    from _contextvars import Context, ContextVar, Token, copy_context\nImportError: /usr/lib/python3.9/lib-dynload/_contextvars.cpython-39-x86_64-linux-gnu.so: undefined symbol: PyContextVar_Type\n","server_host":"ust4hpc-data1","server_pid":186974,"server_timestamp":"2023-06-20T14:45:46.657Z","server_type":"agent"}

The python plugin is linked to python3:

```
root@ust4hpc-data1:~# ldd /usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-python.so  |grep python
	libboost_python39.so.1.78.0 => /opt/irods-externals/boost1.78.0-0/lib/libboost_python39.so.1.78.0 (0x00007f866056f000)
	libpython3.9.so.1.0 => /lib/x86_64-linux-gnu/libpython3.9.so.1.0 (0x00007f865ffbe000)
```

But the package depends on python 2:

```
root@ust4hpc-data1:~# apt-cache depends irods-rule-engine-plugin-python  |grep python
irods-rule-engine-plugin-python
  Depends: <python-dev>
    python-dev-is-python2
```

**Comment by SwooshyCueb** [comment]
This is due to #133. We have the wrong package dependency set for Python. There's a fix in the pipeline

**Comment by SwooshyCueb** [comment]
The fix has been merged and will be included in the next release of the plugin.
