### ISSUE TITLE
IrodsRunpathDefaults

### ISSUE THREAD

**Issue by DOC-MEX** [irods/irods_rule_engine_plugin_python#162]
I am trying a to build a fresh installation but I'm getting this error:
build$ cmake ../
- Using user-specified value for IRODS_EXTERNALS_FULLPATH_CLANG: /opt/irods-externals/clang13.0.0-0
CMake Error at CMakeLists.txt:17 (include):
  include could not find load file:

    IrodsRunpathDefaults

What should be content and format fo this configuration file?

**Comment by korydraughn** [comment]
Sounds like you're building the wrong version of the plugin.

If you're compiling for 4.3.0, `git checkout` a 4.3 tag. If you're compiling for 4.2, checkout a 4.2 tag.

The tag always has the version of the iRODS server it is compatible with.

**Comment by DOC-MEX** [comment]
Thanks, I did not realise that the tag 4.3.0.1 was available, I switched to 4.3.0.0. 
However, another arises when trying to run cmake:

CMake Error at /usr/lib/irods/cmake/Modules/UseLibCXX.cmake:44 (add_link_options):
  Error evaluating generator expression:

    $<LINK_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression
Call Stack (most recent call first):

**Comment by korydraughn** [comment]
Generally you want to use the latest tag for a specific version. In this case, 4.3.0.1.

You may be hitting a CMake caching situation. Try deleting your build directory and starting over.

**Comment by korydraughn** [comment]
Were you able to compile the plugin?
