### ISSUE TITLE
import exifread error

### ISSUE THREAD

**Issue by DOC-MEX** [irods/irods_rule_engine_plugin_python#163]
This a more general question. 
the irods training documentation there is an example for extracting metadata

https://github.com/irods/irods_training/blob/main/beginner/core.py

The example works in an old ubuntu 18 but no in Ubuntu 20. Irods seems to break when trying to import exifread.

The issue seems to be change from python 2 to python 3. Is there solution for this problem? or is there a new implementation for that simple python rule engine example?

**Comment by korydraughn** [comment]
Please share the error output you're seeing.

**Comment by SwooshyCueb** [comment]
This sounds like it could be #136. If so, this is already fixed for 4.3.1. The workaround until 4.3.1 is released is to `LD_PRELOAD` libpython in the server.

**Comment by DOC-MEX** [comment]
the moment I add import exifread to core.py I get these errors

"log_category":"legacy","log_facility":"local0","log_level":"error","log_message":"caught python exception: Traceback (most recent call last):\n  File \"/usr/lib/python3.8/decimal.py\", line 3, in <module>\n    from _decimal import *\nImportError: /usr/lib/python3.8/lib-dynload/_decimal.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyFloat_Type\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/etc/irods/core.py\", line 9, in <module>\n    import exifread\n  File \"/usr/local/lib/python3.8/dist-packages/exifread/__init__.py\", line 9, in <module>\n    from exifread.classes import ExifHeader\n  File \"/usr/local/lib/python3.8/dist-packages/exifread/classes.py\", line 6, in <module>\n    from exifread.utils import Ratio\n  File \"/usr/local/lib/python3.8/dist-packages/exifread/utils.py\", line 5, in <module>\n    from fractions import Fraction\n  File \"/usr/lib/python3.8/fractions.py\", line 6, in <module>\n    from decimal import Decimal\n  File \"/usr/lib/python3.8/decimal.py\", line 8, in <module>\n    from _pydecimal import *\n  File \"/usr/lib/python3.8/_pydecimal.py\", line 440, in <module>\n    import contextvars\n  File \"/usr/lib/python3.8/contextvars.py\", line 1, in <module>\n    from _contextvars import Context, ContextVar, Token, copy_context\nImportError: /usr/lib/python3.8/lib-dynload/_contextvars.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyContextVar_Type\n"

**Comment by korydraughn** [comment]
I agree.

**Comment by trel** [comment]
We'll wait for confirmation before closing and marking as duplicate.

**Comment by DOC-MEX** [comment]
Thanks. It works now.

**Comment by trel** [comment]
Excellent.
