### ISSUE TITLE
Change to python 3

### ISSUE THREAD

**Issue by tempoz** [irods/irods_rule_engine_plugin_python#17]
- [x] Python 2 has end-of-life scheduled for the end of 2019, so we should stop depending on it and move to python 3 sometime in the next year.

- [x] Need to remember to remove the removal of register around `boost::python`:
```
#define register
...
#undef register
```

**Comment by trel** [comment]
this will occur for iRODS 4.3.0

**Comment by alanking** [comment]
I've been using python 3 features with 4.3.1.0 PREP for another project so I feel like this is done?

**Comment by alanking** [comment]
Checkboxed, and closing.
