### ISSUE TITLE
Add section to README explaining/demonstrating how to pass values back to the caller

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_rule_engine_plugin_python#187]
- [x] main
- [x] 4-3-stable

This is achieved by writing a value back _(as a string)_ to the appropriate index within the `rule_args` array. The caller is required to pass one or more variables as out parameters.

Here's an example:
```python
def get_magic_number(rule_args, callback, rei):
    rule_args[0] = '42' # Notice the integer is represented as a string.
```

In the native rule language, you'd call the rule like so.
```python
some_rule()
{
    *magic_number = '-1'; # This is required.
    get_magic_number(*magic_number);
    writeLine('serverLog', 'The magic number is [*magic_number].');
}
```

It's important that the value passed and returned across REP boundaries be of type string. Passing any other type will result in an error.

**Comment by trel** [comment]
note where the `-1` is passed, it could be an empty string.

the 'required' comment is about the string-ness, not the value `-1`.
