### ISSUE TITLE
Install dependencies for building the plugin

### ISSUE THREAD

**Issue by kwaegema** [irods/irods_rule_engine_plugin_python#3]
Maybe interesting for documentation or other people:
On EL7, I first had to install these dependencies before i was able to build the plugin:
``irods-externals* irods-devel gcc-c++ python-devel openssl-devel rpm-build``

I also had to use the cmake of irods-externals-cmake, not the distro cmake, so I did run ``/opt/irods-externals/cmake3.5.2-0/bin/cmake ../`` instead of just ``cmake ../``

**Comment by parena1** [comment]
Thanks for your post, put me in the right direction for Unbuntu 14.04 with these dependencies:
apt-get install irods-externals* irods-devel python-devel g++ build-essential

cd /opt
git clone https://github.com/irods/irods_rule_engine_plugin_python.git
cd irods_rule_engine_plugin_python
mkdir build
cd build
/opt/irods-externals/cmake3.5.2-0/bin/cmake ../
make package
dpkg -i irods-rule-engine-plugin-python-4.2.0-ubuntu14-x86_64.deb

**Comment by trel** [comment]
The CMakeLists.txt file declares the build dependencies.
