### ISSUE TITLE
genquery.py double-executes & fetches completed queries

### ISSUE THREAD

**Issue by cjsmeele** [irods/irods_rule_engine_plugin_python#35]
Current genquery.py `row_iterator` always performs a single extra `msiGetMoreRows` after all rows are consumed (continue index is already <= 0) (https://github.com/irods/irods_rule_engine_plugin_python/blob/master/genquery.py#L81). This appears to cause the query to be re-executed.

The auto-closing code (https://github.com/irods/irods_rule_engine_plugin_python/blob/master/genquery.py#L101) then has to fetch all query results again, since we are always left with an open query.

The issue does not occur when a query is aborted (i.e. a `break` or exception occurs before all rows have been yielded), since the query is never re-opened then.

Based on testing against genquery.py of https://github.com/irods/irods_rule_engine_plugin_python/pull/34 (because I was very curious why there was a performance difference),  I see a 1.94x performance difference for a query with 9308 result rows, when all rows are consumed ([test rule](https://gist.github.com/cjsmeele/6cff2ea82706903e576811f771aecc08), [data](https://gist.github.com/cjsmeele/619195c4d655fc2090a0bbf8e3f4c206)).

**Comment by trel** [comment]
the new Query iterator class handles this cleanly now.   thanks!   closing.
