### ISSUE TITLE
compiling inside the irods_development_environment (centos7) hangs

### ISSUE THREAD

**Issue by wccropper** [irods/irods_rule_engine_plugin_python#37]
I have built the docker environemnt for building the RPMS. It is working well for the base packages, storage_tiering and s3. But it is not building the python rule engine. it seems to hang at the following section:

[ 66%] Building CXX object CMakeFiles/irods_rule_engine_plugin-python.dir/irods_types.cpp.o
/irods_rule_engine_plugin_python/irods_types.cpp:3:9: warning: 'BOOST_SYSTEM_NO_DEPRECATED' macro redefined [-Wmacro-redefined]
#define BOOST_SYSTEM_NO_DEPRECATED BOOST_PYTHON_MAX_ARITY 45
        ^
<command line>:1:9: note: previous definition is here
#define BOOST_SYSTEM_NO_DEPRECATED 1
        ^
In file included from /irods_rule_engine_plugin_python/irods_types.cpp:7:
In file included from /opt/irods-externals/boost1.67.0-0/include/boost/python/module_init.hpp:8:
In file included from /opt/irods-externals/boost1.67.0-0/include/boost/python/detail/prefix.hpp:13:
In file included from /opt/irods-externals/boost1.67.0-0/include/boost/python/detail/wrap_python.hpp:50:
In file included from /usr/include/python2.7/pyconfig.h:6:
/usr/include/python2.7/pyconfig-64.h:1191:9: warning: '_POSIX_C_SOURCE' macro redefined [-Wmacro-redefined]
#define _POSIX_C_SOURCE 200112L
        ^
/usr/include/features.h:168:10: note: previous definition is here
# define _POSIX_C_SOURCE        200809L
         ^
In file included from /irods_rule_engine_plugin_python/irods_types.cpp:7:
In file included from /opt/irods-externals/boost1.67.0-0/include/boost/python/module_init.hpp:8:
In file included from /opt/irods-externals/boost1.67.0-0/include/boost/python/detail/prefix.hpp:13:
In file included from /opt/irods-externals/boost1.67.0-0/include/boost/python/detail/wrap_python.hpp:50:
In file included from /usr/include/python2.7/pyconfig.h:6:
/usr/include/python2.7/pyconfig-64.h:1213:9: warning: '_XOPEN_SOURCE' macro redefined [-Wmacro-redefined]
#define _XOPEN_SOURCE 600
        ^
/usr/include/features.h:170:10: note: previous definition is here
# define _XOPEN_SOURCE  700
         ^
In file included from /irods_rule_engine_plugin_python/irods_types.cpp:7:
In file included from /opt/irods-externals/boost1.67.0-0/include/boost/python/module_init.hpp:8:
In file included from /opt/irods-externals/boost1.67.0-0/include/boost/python/detail/prefix.hpp:13:
In file included from /opt/irods-externals/boost1.67.0-0/include/boost/python/detail/wrap_python.hpp:151:
In file included from /usr/include/python2.7/Python.h:85:
/usr/include/python2.7/unicodeobject.h:534:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register PyObject *obj,     /* Object */
    ^~~~~~~~~
/usr/include/python2.7/unicodeobject.h:553:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register PyObject *obj      /* Object */
    ^~~~~~~~~
/usr/include/python2.7/unicodeobject.h:575:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register const wchar_t *w,  /* wchar_t buffer */
    ^~~~~~~~~
/usr/include/python2.7/unicodeobject.h:593:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register wchar_t *w,        /* wchar_t buffer */
    ^~~~~~~~~
In file included from /irods_rule_engine_plugin_python/irods_types.cpp:7:
In file included from /opt/irods-externals/boost1.67.0-0/include/boost/python/module_init.hpp:8:
In file included from /opt/irods-externals/boost1.67.0-0/include/boost/python/detail/prefix.hpp:13:
In file included from /opt/irods-externals/boost1.67.0-0/include/boost/python/detail/wrap_python.hpp:151:
In file included from /usr/include/python2.7/Python.h:94:
/usr/include/python2.7/stringobject.h:173:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register PyObject *obj,     /* string or Unicode object */
    ^~~~~~~~~
/usr/include/python2.7/stringobject.h:174:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register char **s,          /* pointer to buffer variable */
    ^~~~~~~~~
/usr/include/python2.7/stringobject.h:175:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register Py_ssize_t *len    /* pointer to length variable or NULL
    ^~~~~~~~~

**Comment by wccropper** [comment]
It seems it did build but takes almost an hour to compile. Not sure if this is normal, but I will test the package and make sure it works.

**Comment by trel** [comment]
Yes, the templated C++ takes a long time to compile.
