### ISSUE TITLE
Build fails, find_package(IRODS 4.3.0 REQUIRED) in CMakeList.txt

### ISSUE THREAD

**Issue by TD-er** [irods/irods_rule_engine_plugin_python#5]
The build fails, because no iRODS 4.3.0 can be found.

`CMake Error at CMakeLists.txt (find_package):", " Could not find a configuration file for package \"IRODS\" that is compatible", " with requested version \"4.3.0\".", "", " The following configuration files were considered but not accepted:", "", " /usr/lib/irods/cmake/IRODSConfig.cmake, version: 4.2.0"`

**Comment by TD-er** [comment]
I have tried to build it with the required version of iRODS set to 4.2.0 and it still won't build. Some function signatures have apparently changed. 
So I like to know what version of iRODS will be supported.
We are investigating Python rules to be used in a new setup with iRODS and knowing the supported version will have impact on the rule-language used in our project.

**Comment by trel** [comment]
The build is being resolved right now in testing.  Expect a few commits within the next couple days to resolve this problem.  We are closing in on release of iRODS 4.2.1 and this rule engine will require 4.2.1.

Any python rules you have written with the earlier codebase may need new signatures (the earlier code only handled a subset of types).  Other than that, the behavior will be very similar.

I'll leave this open until the code is pushed.

**Comment by trel** [comment]
The refactor and additional functionality is now pushed.

The requirement is now marked as 4.2.1 and this will be the case through release.
