### ISSUE TITLE
Need symbolic access to irods error and state tables

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_rule_engine_plugin_python#58]
- [x] master
- [x] 4-2-stable
------
Python Rule Engine Plugin currently must use error codes copied from `rodsErrorTable.h` or `irods_state_table.h` ; it would be better to enable programmatic, symbolic access to these constants whether in a module or microservice.
Compare [irods/irods#5043]( https://github.com/irods/irods/issues/5043)

**Comment by d-w-moore** [comment]
@trel could you assign me? seeing as I seeminly already have a fix : )

**Comment by trel** [comment]
@d-w-moore two merged - checkbox and close if complete.

**Comment by trel** [comment]
ah, awaiting merging in the irods/irods repo
