### ISSUE TITLE
Split irods_types.cpp class_ and enum_ definitions into multiple files

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_rule_engine_plugin_python#84]
`irods_types.cpp` takes a disgusting amount of time to compile. To fix this, we should follow Boost's guidance and split it up into multiple files:
https://www.boost.org/doc/libs/1_76_0/libs/python/doc/html/tutorial/tutorial/techniques.html#tutorial.techniques.reducing_compiling_time

**Comment by trel** [comment]
do we have a before and after elapsed time?
